In [19]:
import os , glob 
import pandas as pd
from  matplotlib import pyplot as plt
import seaborn as sns
import numpy as np

In [20]:
path = "c:\\"

In [21]:

all_files = glob.glob(os.path.join(path,"*.csv"))

In [22]:
all_df = []

In [23]:
for f in all_files:
    df = pd.read_csv(f,sep =',')
    df['file'] = f.split('/') [-1]
    all_df.append(df)

In [24]:
merged_df = pd.concat(all_df,ignore_index = True , sort = True)

In [25]:
merged_df

,AWD,Coastal_population,Code,Commissioning date,Country,Economic_status,Entity,GPWP,Hub height (m),IMPW,...,WT,Year,file,glass,metals,paper_paperboard,plastic,type_id,wood,year
0,1948510.0,2530533.0,NaN,NaN,Albania,LMI,NaN,NaN,NaN,NaN,...,NaN,NaN,c:\All_Waste_Day.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19867896.0,16556580.0,NaN,NaN,Algeria,UMI,NaN,NaN,NaN,NaN,...,NaN,NaN,c:\All_Waste_Day.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1819220.0,3790041.0,NaN,NaN,Angola,LMI,NaN,NaN,NaN,NaN,...,NaN,NaN,c:\All_Waste_Day.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,30578.0,14561.0,NaN,NaN,Anguilla,HIC,NaN,NaN,NaN,NaN,...,NaN,NaN,c:\All_Waste_Day.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,367637.0,66843.0,NaN,NaN,Antigua & Barbuda,HIC,NaN,NaN,NaN,NaN,...,NaN,NaN,c:\All_Waste_Day.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,landfilled,NaN,c:\Waste_type.csv,6820000.0,11950000.0,19380000.0,24240000.0,4.0,10880000.0,2011.0
7963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,landfilled,NaN,c:\Waste_type.csv,6900000.0,12190000.0,19490000.0,24260000.0,4.0,10860000.0,2012.0
7964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,landfilled,NaN,c:\Waste_type.csv,6940000.0,12740000.0,20160000.0,24810000.0,4.0,10800000.0,2013.0
7965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,landfilled,NaN,c:\Waste_type.csv,7040000.0,12860000.0,19470000.0,25190000.0,4.0,11010000.0,2014.0
7966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,landfilled,NaN,c:\Waste_type.csv,6970000.0,13070000.0,18280000.0,26010000.0,4.0,11060000.0,2015.0

In [26]:
#loading file from path
data = pd.read_csv("c:\\Country_plastic_details.csv")
data1 = pd.read_csv("c:\\Mismanaged_Ocean.csv")
data2 = pd.read_csv("c:\\Proportion_Kg_Day.csv")
data2

     Unnamed: 0            Country      PMPW     PMSPW
0             0            Albania  0.533321  0.466679
1             1            Algeria  0.399306  0.600694
2             2             Angola  0.272848  0.727152
3             3           Anguilla  0.961412  0.038588
4             4  Antigua & Barbuda  0.921836  0.078164
..          ...                ...       ...       ...
187         187               USVI  0.979663  0.020337
188         188            Vanuatu  0.167043  0.832957
189         189          Venezuela  0.930586  0.069414
190         190            Vietnam  0.120817  0.879183
191         191              Yemen  0.250994  0.749006

[192 rows x 4 columns]

In [27]:
#viewing Dataset1

data

,Country,Economic_status,Coastal_population,WG,PWS,IMW,LW,WG.1,PWG,IMPW,PWL,MPW,MPW2010,MPW2025
0,Albania,LMI,2530533.0,0.77,9.0,45.0,2.0,1948510.0,174392.0,77897.0,3488.0,0.03,29705,63051
1,Algeria,UMI,16556580.0,1.20,12.0,58.0,2.0,19867896.0,2374214.0,1378693.0,47484.0,0.09,520555,1017444
2,Angola,LMI,3790041.0,0.48,13.0,71.0,2.0,1819220.0,235589.0,166597.0,4712.0,0.05,62528,136770
3,Anguilla,HIC,14561.0,2.10,12.0,2.0,2.0,30578.0,3654.0,68.0,73.0,0.01,52,73
4,Antigua & Barbuda,HIC,66843.0,5.50,12.0,6.0,2.0,367637.0,43933.0,2555.0,879.0,0.05,1253,1385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,Vanuatu,LMI,251851.0,3.28,9.0,81.0,2.0,826071.0,73933.0,60104.0,1479.0,0.25,22478,38006
189,Venezuela,HIC,16094897.0,2.10,12.0,5.0,2.0,33799284.0,4039014.0,199585.0,80780.0,0.02,102333,154243
190,Vietnam,LMI,55858245.0,0.79,13.0,86.0,2.0,44128014.0,5714578.0,4909870.0,114292.0,0.09,1833819,4172828
191,Yemen,LMI,6048920.0,0.79,13.0,73.0,2.0,4778647.0,618835.0,451134.0,12377.0,0.08,169181,513907
192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,31865274,69143290

In [28]:
#viewing Dataset1

data1

,Unnamed: 0,Country,Mismanaged_plastic_waste_kg/person/day,Mismanaged_plastic_waste_lb/person/day,MPWO
0,0,Albania,0.03,0.07,0.02
1,1,Algeria,0.09,0.20,0.05
2,2,Angola,0.05,0.11,0.03
3,3,Anguilla,0.01,0.02,0.00
4,4,Antigua & Barbuda,0.05,0.11,0.03
...,...,...,...,...,...
187,187,USVI,0.01,0.02,0.00
188,188,Vanuatu,0.25,0.55,0.14
189,189,Venezuela,0.02,0.04,0.01
190,190,Vietnam,0.09,0.20,0.05
191,191,Yemen,0.08,0.18,0.04

In [29]:
#viewing Dataset2
data2

     Unnamed: 0            Country      PMPW     PMSPW
0             0            Albania  0.533321  0.466679
1             1            Algeria  0.399306  0.600694
2             2             Angola  0.272848  0.727152
3             3           Anguilla  0.961412  0.038588
4             4  Antigua & Barbuda  0.921836  0.078164
..          ...                ...       ...       ...
187         187               USVI  0.979663  0.020337
188         188            Vanuatu  0.167043  0.832957
189         189          Venezuela  0.930586  0.069414
190         190            Vietnam  0.120817  0.879183
191         191              Yemen  0.250994  0.749006

[192 rows x 4 columns]

In [30]:
#combining Dataset
output  = pd.merge(data,data1, on ='Country', how = 'inner' )
output

,Country,Economic_status,Coastal_population,WG,PWS,IMW,LW,WG.1,PWG,IMPW,PWL,MPW,MPW2010,MPW2025,Unnamed: 0,Mismanaged_plastic_waste_kg/person/day,Mismanaged_plastic_waste_lb/person/day,MPWO
0,Albania,LMI,2530533.0,0.77,9.0,45.0,2.0,1948510.0,174392.0,77897.0,3488.0,0.03,29705,63051,0,0.03,0.07,0.02
1,Algeria,UMI,16556580.0,1.20,12.0,58.0,2.0,19867896.0,2374214.0,1378693.0,47484.0,0.09,520555,1017444,1,0.09,0.20,0.05
2,Angola,LMI,3790041.0,0.48,13.0,71.0,2.0,1819220.0,235589.0,166597.0,4712.0,0.05,62528,136770,2,0.05,0.11,0.03
3,Anguilla,HIC,14561.0,2.10,12.0,2.0,2.0,30578.0,3654.0,68.0,73.0,0.01,52,73,3,0.01,0.02,0.00
4,Antigua & Barbuda,HIC,66843.0,5.50,12.0,6.0,2.0,367637.0,43933.0,2555.0,879.0,0.05,1253,1385,4,0.05,0.11,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,USVI,HIC,134219.0,2.10,12.0,0.0,2.0,281860.0,33682.0,11.0,674.0,0.01,250,296,187,0.01,0.02,0.00
188,Vanuatu,LMI,251851.0,3.28,9.0,81.0,2.0,826071.0,73933.0,60104.0,1479.0,0.25,22478,38006,188,0.25,0.55,0.14
189,Venezuela,HIC,16094897.0,2.10,12.0,5.0,2.0,33799284.0,4039014.0,199585.0,80780.0,0.02,102333,154243,189,0.02,0.04,0.01
190,Vietnam,LMI,55858245.0,0.79,13.0,86.0,2.0,44128014.0,5714578.0,4909870.0,114292.0,0.09,1833819,4172828,190,0.09,0.20,0.05
191,Yemen,LMI,6048920.0,0.79,13.0,73.0,2.0,4778647.0,618835.0,451134.0,12377.0,0.08,169181,513907,191,0.08,0.18,0.04

In [31]:
#combinging 2 dataset
output1 = pd.merge(output,data2, on = 'Country', how = 'inner')
output1

,Country,Economic_status,Coastal_population,WG,PWS,IMW,LW,WG.1,PWG,IMPW,...,MPW,MPW2010,MPW2025,Unnamed: 0_x,Mismanaged_plastic_waste_kg/person/day,Mismanaged_plastic_waste_lb/person/day,MPWO,Unnamed: 0_y,PMPW,PMSPW
0,Albania,LMI,2530533.0,0.77,9.0,45.0,2.0,1948510.0,174392.0,77897.0,...,0.03,29705,63051,0,0.03,0.07,0.02,0,0.533321,0.466679
1,Algeria,UMI,16556580.0,1.20,12.0,58.0,2.0,19867896.0,2374214.0,1378693.0,...,0.09,520555,1017444,1,0.09,0.20,0.05,1,0.399306,0.600694
2,Angola,LMI,3790041.0,0.48,13.0,71.0,2.0,1819220.0,235589.0,166597.0,...,0.05,62528,136770,2,0.05,0.11,0.03,2,0.272848,0.727152
3,Anguilla,HIC,14561.0,2.10,12.0,2.0,2.0,30578.0,3654.0,68.0,...,0.01,52,73,3,0.01,0.02,0.00,3,0.961412,0.038588
4,Antigua & Barbuda,HIC,66843.0,5.50,12.0,6.0,2.0,367637.0,43933.0,2555.0,...,0.05,1253,1385,4,0.05,0.11,0.03,4,0.921836,0.078164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,USVI,HIC,134219.0,2.10,12.0,0.0,2.0,281860.0,33682.0,11.0,...,0.01,250,296,187,0.01,0.02,0.00,187,0.979663,0.020337
188,Vanuatu,LMI,251851.0,3.28,9.0,81.0,2.0,826071.0,73933.0,60104.0,...,0.25,22478,38006,188,0.25,0.55,0.14,188,0.167043,0.832957
189,Venezuela,HIC,16094897.0,2.10,12.0,5.0,2.0,33799284.0,4039014.0,199585.0,...,0.02,102333,154243,189,0.02,0.04,0.01,189,0.930586,0.069414
190,Vietnam,LMI,55858245.0,0.79,13.0,86.0,2.0,44128014.0,5714578.0,4909870.0,...,0.09,1833819,4172828,190,0.09,0.20,0.05,190,0.120817,0.879183
191,Yemen,LMI,6048920.0,0.79,13.0,73.0,2.0,4778647.0,618835.0,451134.0,...,0.08,169181,513907,191,0.08,0.18,0.04,191,0.250994,0.749006

In [32]:
#removing Unamed_column from Dataset
data_merged = output1.drop("Unnamed: 0_x",axis=1)
data_merged

,Country,Economic_status,Coastal_population,WG,PWS,IMW,LW,WG.1,PWG,IMPW,PWL,MPW,MPW2010,MPW2025,Mismanaged_plastic_waste_kg/person/day,Mismanaged_plastic_waste_lb/person/day,MPWO,Unnamed: 0_y,PMPW,PMSPW
0,Albania,LMI,2530533.0,0.77,9.0,45.0,2.0,1948510.0,174392.0,77897.0,3488.0,0.03,29705,63051,0.03,0.07,0.02,0,0.533321,0.466679
1,Algeria,UMI,16556580.0,1.20,12.0,58.0,2.0,19867896.0,2374214.0,1378693.0,47484.0,0.09,520555,1017444,0.09,0.20,0.05,1,0.399306,0.600694
2,Angola,LMI,3790041.0,0.48,13.0,71.0,2.0,1819220.0,235589.0,166597.0,4712.0,0.05,62528,136770,0.05,0.11,0.03,2,0.272848,0.727152
3,Anguilla,HIC,14561.0,2.10,12.0,2.0,2.0,30578.0,3654.0,68.0,73.0,0.01,52,73,0.01,0.02,0.00,3,0.961412,0.038588
4,Antigua & Barbuda,HIC,66843.0,5.50,12.0,6.0,2.0,367637.0,43933.0,2555.0,879.0,0.05,1253,1385,0.05,0.11,0.03,4,0.921836,0.078164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,USVI,HIC,134219.0,2.10,12.0,0.0,2.0,281860.0,33682.0,11.0,674.0,0.01,250,296,0.01,0.02,0.00,187,0.979663,0.020337
188,Vanuatu,LMI,251851.0,3.28,9.0,81.0,2.0,826071.0,73933.0,60104.0,1479.0,0.25,22478,38006,0.25,0.55,0.14,188,0.167043,0.832957
189,Venezuela,HIC,16094897.0,2.10,12.0,5.0,2.0,33799284.0,4039014.0,199585.0,80780.0,0.02,102333,154243,0.02,0.04,0.01,189,0.930586,0.069414
190,Vietnam,LMI,55858245.0,0.79,13.0,86.0,2.0,44128014.0,5714578.0,4909870.0,114292.0,0.09,1833819,4172828,0.09,0.20,0.05,190,0.120817,0.879183
191,Yemen,LMI,6048920.0,0.79,13.0,73.0,2.0,4778647.0,618835.0,451134.0,12377.0,0.08,169181,513907,0.08,0.18,0.04,191,0.250994,0.749006

In [33]:
#removing Unamed_column from Dataset
data = data_merged.drop("Unnamed: 0_y",axis=1)
data

,Country,Economic_status,Coastal_population,WG,PWS,IMW,LW,WG.1,PWG,IMPW,PWL,MPW,MPW2010,MPW2025,Mismanaged_plastic_waste_kg/person/day,Mismanaged_plastic_waste_lb/person/day,MPWO,PMPW,PMSPW
0,Albania,LMI,2530533.0,0.77,9.0,45.0,2.0,1948510.0,174392.0,77897.0,3488.0,0.03,29705,63051,0.03,0.07,0.02,0.533321,0.466679
1,Algeria,UMI,16556580.0,1.20,12.0,58.0,2.0,19867896.0,2374214.0,1378693.0,47484.0,0.09,520555,1017444,0.09,0.20,0.05,0.399306,0.600694
2,Angola,LMI,3790041.0,0.48,13.0,71.0,2.0,1819220.0,235589.0,166597.0,4712.0,0.05,62528,136770,0.05,0.11,0.03,0.272848,0.727152
3,Anguilla,HIC,14561.0,2.10,12.0,2.0,2.0,30578.0,3654.0,68.0,73.0,0.01,52,73,0.01,0.02,0.00,0.961412,0.038588
4,Antigua & Barbuda,HIC,66843.0,5.50,12.0,6.0,2.0,367637.0,43933.0,2555.0,879.0,0.05,1253,1385,0.05,0.11,0.03,0.921836,0.078164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,USVI,HIC,134219.0,2.10,12.0,0.0,2.0,281860.0,33682.0,11.0,674.0,0.01,250,296,0.01,0.02,0.00,0.979663,0.020337
188,Vanuatu,LMI,251851.0,3.28,9.0,81.0,2.0,826071.0,73933.0,60104.0,1479.0,0.25,22478,38006,0.25,0.55,0.14,0.167043,0.832957
189,Venezuela,HIC,16094897.0,2.10,12.0,5.0,2.0,33799284.0,4039014.0,199585.0,80780.0,0.02,102333,154243,0.02,0.04,0.01,0.930586,0.069414
190,Vietnam,LMI,55858245.0,0.79,13.0,86.0,2.0,44128014.0,5714578.0,4909870.0,114292.0,0.09,1833819,4172828,0.09,0.20,0.05,0.120817,0.879183
191,Yemen,LMI,6048920.0,0.79,13.0,73.0,2.0,4778647.0,618835.0,451134.0,12377.0,0.08,169181,513907,0.08,0.18,0.04,0.250994,0.749006

In [34]:
#data of top 15 Countries
data = data.head(15)
data

,Country,Economic_status,Coastal_population,WG,PWS,IMW,LW,WG.1,PWG,IMPW,PWL,MPW,MPW2010,MPW2025,Mismanaged_plastic_waste_kg/person/day,Mismanaged_plastic_waste_lb/person/day,MPWO,PMPW,PMSPW
0,Albania,LMI,2530533.0,0.77,9.0,45.0,2.0,1948510.0,174392.0,77897.0,3488.0,0.03,29705,63051,0.03,0.07,0.02,0.533321,0.466679
1,Algeria,UMI,16556580.0,1.20,12.0,58.0,2.0,19867896.0,2374214.0,1378693.0,47484.0,0.09,520555,1017444,0.09,0.20,0.05,0.399306,0.600694
2,Angola,LMI,3790041.0,0.48,13.0,71.0,2.0,1819220.0,235589.0,166597.0,4712.0,0.05,62528,136770,0.05,0.11,0.03,0.272848,0.727152
3,Anguilla,HIC,14561.0,2.10,12.0,2.0,2.0,30578.0,3654.0,68.0,73.0,0.01,52,73,0.01,0.02,0.00,0.961412,0.038588
4,Antigua & Barbuda,HIC,66843.0,5.50,12.0,6.0,2.0,367637.0,43933.0,2555.0,879.0,0.05,1253,1385,0.05,0.11,0.03,0.921836,0.078164
5,Argentina,UMI,16449245.0,1.22,15.0,12.0,2.0,20068079.0,3000178.0,372261.0,60004.0,0.03,157777,320197,0.03,0.07,0.02,0.855920,0.144080
6,Aruba,HIC,137910.0,2.10,12.0,1.0,2.0,289611.0,34609.0,326.0,692.0,0.01,372,476,0.01,0.02,0.00,0.970586,0.029414
7,Australia,HIC,17235954.0,2.23,5.0,0.0,2.0,38436177.0,1902591.0,0.0,38052.0,0,13889,24653,0.00,0.00,0.00,0.980000,0.020000
8,Bahamas,HIC,341145.0,3.25,12.0,1.0,2.0,1108721.0,132492.0,1002.0,2650.0,0.01,1333,1718,0.01,0.02,0.00,0.972436,0.027564
9,Bahrain,HIC,743574.0,1.10,12.0,10.0,2.0,817931.0,97743.0,10033.0,1955.0,0.02,4376,9915,0.02,0.04,0.01,0.877352,0.122648
10,Bangladesh,LI,70874124.0,0.43,8.0,87.0,2.0,30475873.0,2422832.0,2108603.0,48457.0,0.03,787327,2210230,0.03,0.07,0.02,0.109695,0.890305
11,Barbados,HIC,276784.0,4.75,12.0,4.0,2.0,1314724.0,157110.0,6400.0,3142.0,0.03,3483,3719,0.03,0.07,0.02,0.939265,0.060735
12,Belgium,HIC,4747957.0,1.33,6.0,0.0,2.0,6314783.0,375730.0,0.0,7515.0,0,2743,5739,0.00,0.00,0.00,0.979999,0.020001
13,Belize,UMI,202429.0,2.87,6.0,29.0,2.0,580971.0,34568.0,9972.0,691.0,0.05,3892,6042,0.05,0.11,0.03,0.691536,0.308464
14,Benin,LI,3235418.0,0.54,8.0,83.0,2.0,1747126.0,138896.0,115073.0,2778.0,0.04,43015,119467,0.04,0.09,0.02,0.151516,0.848484

ValueError: invalid literal for int() with base 10: '0.03'